@startuml

!includeurl https://gist.githubusercontent.com/Arnaud-Bonneuil/c317a7a30bed7d64e2b5b1f558ac00cf/raw/sober.plantuml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/Class_Triggered_Timer/main/doc/Class_Triggered_Timer.puml

skinparam groupInheritance 2

interface Delay_Is_Up <<Event_Interface>>
{
  Sent when a Class_Delay delay has ended,
  i.e. that the output in equal to the input.
}

abstract class Class_Delay <<Internal_Design_Class>>
{
  Allows to apply some delay to the changes of a boolean data.
  --
  + Delay_Duration:uint32
  --
  {abstract} + Set()
  {abstract} + Reset()
  + Get( OUT output:boolean )
  {abstract} + Time_Is_Up()
}

class Class_Turn_On_Delay <<Internal_Design_Class>>
{
  Allows to set a boolean value with a delay.
  The reset is immediate.
}

class Class_Turn_Off_Delay <<Internal_Design_Class>>
{
  Allows to reset a boolean value with a delay.
  The set is immediate.
}

class Class_Turn_On_Off_Delay <<Internal_Design_Class>>
{
  Allows to set and reset a boolean value with a delay.
  --
  + Off_Delay_Duration:uint32
}

Delay_Is_Up <.. Class_Delay: <<send>>

Class_Delay ..> Time_Is_Up : <<receive>>

Class_Delay -up-> "1\rMy_Timer" Class_Triggered_Timer

Class_Delay <|-- Class_Turn_On_Delay
Class_Delay <|-- Class_Turn_Off_Delay
Class_Delay <|-- Class_Turn_On_Off_Delay

@enduml