@startuml

!includeurl https://gist.githubusercontent.com/Arnaud-Bonneuil/c317a7a30bed7d64e2b5b1f558ac00cf/raw/sober.puml

!includeurl https://raw.githubusercontent.com/HomeMadeBots/Timers/main/doc/Triggered_Timer.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/Timers/main/doc/Time_Is_Up.puml

!includeurl https://raw.githubusercontent.com/HomeMadeBots/Delays/main/doc/Delay_Is_Up.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/Delays/main/doc/Delay.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/Delays/main/doc/Turn_On_Delay.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/Delays/main/doc/Turn_Off_Delay.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/Delays/main/doc/Turn_On_Off_Delay.puml

skinparam groupInheritance 2

Triggered_Timer ..> Time_Is_Up : <<send>>

Delay_Is_Up <.. Delay: <<send>>

Delay ..> Time_Is_Up : <<receive>>

Delay -up-> "1\rMy_Timer" Triggered_Timer

Delay <|-- Turn_On_Delay
Delay <|-- Turn_Off_Delay
Delay <|-- Turn_On_Off_Delay

@enduml