@startuml

!includeurl https://gist.githubusercontent.com/Arnaud-Bonneuil/c317a7a30bed7d64e2b5b1f558ac00cf/raw/sober.puml

title Class_Turn_On_Delay cancel //Set()//

caption

turn on delay = 10s (//Delay_Duration// = 10000)
end caption

concise User
robust Output
Output has ON
Output has OFF

@0
Output is ON

@5
User --> Output : Reset()
Output is OFF

@10
User --> Output : Set()

@15
User --> Output : Reset()

User@10 <->@15 : {<10s}

@20
Output is OFF

@enduml
