@startuml

!includeurl https://gist.githubusercontent.com/Arnaud-Bonneuil/c317a7a30bed7d64e2b5b1f558ac00cf/raw/sober.puml

<style>
  caption
  {
    Margin 20 0 0 0 
    HorizontalAlignment left
  }
</style>

title Class_Turn_On_Delay multiple //Set()//

caption
turn on delay = 10s (//Delay_Duration// = 10000)
end caption

concise User
robust Output


@0
Output is OFF

@5
User --> Output : Set()

@10
User --> Output : Set()

@15
Output is ON

User@5<->@15 : 10s

@20
User --> Output : Set()

@25
User --> Output : Reset()
Output is OFF


@enduml
